// Store configuration - Generated by EpicMerch Storefront Builder
export const storeConfig = {
  name: 'rtestst',
  description: 'Welcome to Epic Threadz',
  
  // API Configuration
  api: {
    key: 'pk_live_f5722a3df0142d1dbb3f6a660431627e',
    endpoint: 'https://api.epicmerch.com/api'
  },
  
  // Currency
  currency: 'USD',
  currencySymbol: '$',
  
  // Theme
  theme: {
    style: 'playful',
    darkMode: false,
    colors: {
      primary: '#6366f1',
      secondary: '#4f46e5',
      accent: '#f59e0b',
      background: '#ffffff',
      text: '#1f2937'
    }
  },
  
  // Layout
  layout: {
    type: 'grid',
    navigation: 'sticky',
    footer: 'detailed',
    heroStyle: 'fullWidth',
    productCardStyle: 'detailed'
  },
  
  // Features
  features: {
    wishlist: false,
    reviews: false,
    search: true,
    filters: false,
    quickView: true,
    newsletter: true,
    animations: true
  },
  
  // Sections
  sections: ["hero","featuredProducts","categories","newsletter"],
  
  // Contact
  contact: {
    email: 'owner@epicthreadz.com'
  }
};

export default storeConfig;
